
  /*
  This file is part of "GMP Clearview" package.
  Copyright (C)  2025 Infotrust 
  Alina Zilbergerts, Trish Dothkar,
  -- */


config {
    type: "incremental",
    tags: ["wam","reporting", "prod"],
    database: dataform.projectConfig.vars.OUTPUT_PROJECT,
    schema: dataform.projectConfig.vars.REPORTING_DATASET,
    dependencies: ["base_ga4_events"],
    bigquery: {
      partitionBy: "date"
     //labels: require("includes/core/helpers.js").helpers.storageLabels()
    }
}

js {
    const { helpers } = require("includes/core/helpers");
    const config = helpers.getConfig();
}

/* incrementality */
pre_operations {
  declare date_checkpoint DATE;
--   set @@query_label = "${helpers.executionLabels()}";
  set date_checkpoint = (
    ${when(incremental(),
      `select coalesce(max(date) - ${config.DATA_IS_FINAL_DAYS}, date('${config.GA4_START_DATE}')) from ${self()}`,
      `select date('${config.GA4_START_DATE}')`)}   /* the default, when it's not incremental */
  );
    -- delete some older data, since this may be updated later by GA4
  ${
    when(incremental(),
      `delete from ${self()} where date >= date_checkpoint`
      )
  }
}


SELECT
  event_date AS date, 
  lower(event_params_custom.fulfillment_method) as order_fulfillment,
  --sum(ecommerce.purchase_revenue_in_usd) as revenue,
  SUM(ecommerce.purchase_revenue)   - IFNULL(SUM(ecommerce.shipping_value), 0)   - IFNULL(SUM(ecommerce.tax_value), 0) AS revenue, -- 6/26/26 Revenue should exclude shipping and tax per Elvis
  count(ecommerce.transaction_id) as orders,

FROM ${ref("base_ga4_events")}
where event_date >= date_checkpoint 
AND event_name='purchase'  

group by 1,2
