
  /*
  This file is part of "GMP Clearview" package.
  Copyright (C)  2025 Infotrust 
  Alina Zilbergerts, Trish Dothkar,
  -- */


config {
    type: "view",
    tags: ["wam","reporting"],
    // materialized: true,
    schema: "gmp_reporting"
}
SELECT
  DATE(TIMESTAMP_MICROS(event_timestamp)) AS event_date, 
  lower(event_params_custom.fullfillment_method) as order_fulfillment,
  sum(ecommerce.purchase_revenue_in_usd) as revenue,
  count(ecommerce.transaction_id) as orders,

FROM ${ref("base_ga4_events")}
  where event_name='purchase'  

  group by 1,2
  order by 1,2